### ISSUE TITLE
Warning under DMCA

### ISSUE THREAD

**Issue by xHyroM** [discom-development/discom#1]
I was just looking for `@discordjs/ts-docgen` and suddenly came across it being used by this organization (more specifically this repo). So I went to take a look and noticed a rather strange README, package.json and code that is downloaded from https://github.com/Garlic-Team/GCommands.

Admittedly this repository does not maintain the latest GCommands version v9, but rather v8 still this is a violation of our license. v9 has been out for over a month now, but that doesn't entitle you to download the code and appropriate it and distribute it as your own.

Your code may not be 100% identical because you copied it and converted it to TypeScript, but it still counts as totally stolen code from https://github.com/Garlic-Team/gcommands/tree/v8 only in TS.

We also can't not talk about the guide, which is __totally__ identical to our former guide.
The guide for GCommands v8 was mainly worked on by https://github.com/Gabe616/ (the pog fish#9103, 853550207039832084) who is also pretty pissed off.

Ours: https://garlic-team.js.org/guide/gcommands-legacy/commands/gettingstarted.html

Yours: https://discom.rocks/guide/commands/gettingstarted.html

And just because you may have changed the cmdDir from loader to purely `GCommandsClient#Options` (with your `DiscomClient#Options`) doesn't mean you are entitled to steal all the code and then appropriate it.

---

Speaking of which, I noticed that on your personal account there is https://github.com/RapidFuge/kandler which is also already an exact copy in javascript with renamed methods. By archiving the repo there I can no longer create an issue, but I ask you to unarchive it, edit the README to the official link https://github.com/Garlic-Team/GCommands and do the same with the npm package.

---

However, this repository does not meet the requirements of the `ISC` license under which [GCommands](https://github.com/Garlic-Team/GCommands) falls. The license can be viewed [here](https://github.com/Garlic-Team/gcommands/blob/next/LICENSE)

Also, this repository transforms our `ISC` license into the `MIT` license:
https://github.com/discom-development/discom/blob/4b3bfa0503ff076c95276f15d2cae91deb63e3c1/package.json#L48

You have 7 days to resolve this situation.  
If you want, you can connect to our [discord server](https://discord.com/invite/AjKJSBbGm2) where we can resolve it, but feel free to resolve it here as well.

---

Now a bit more from my point of view. I don\`t think it\`s normal to steal code when it`s also open source and distribute it as your own, thus violating the license. When you have some stuff you'd like to add to GCommands, just fork the repository and create a PR with that stuff. This system of yours is not beneficial to the ecosystem and certainly doesn't respect the license.

**Comment by Gabe616** [comment]
I've also noticed that you copied our GCommands v8 guide, which I wrote.
By the time I'm writing this, the guide has mysteriously disappeared. But, this can still be reverted with evidence.

**You have 7 days, and we will keep an close eye on you from now.**

**Comment by xHyroM** [comment]
cc @RapidFuge

**Comment by RapidFuge** [comment]
Whatever bro your handler/framework whatever sucked anyway, you're 3-5 people fucking code better so nothing like this ever happens again. I'll delete all of this tomorrow so you get a chance to gloat at this shitshow

**Comment by RapidFuge** [comment]
Also I didn't steal your v8 code that was a goner I stole your v7 code and made it better than what V8 was supposed to be. I don't care if the code looked ugly and or horrible it still worked better than what you even tried it to be. and it was still in MIT I don't think that stops all of this but it was still in MIT when I got it. Code better morons
